bioimageio_core_version: 0.5.3post2
bioimageio_spec_version: 0.4.5post6
error: name '_validate_input_shape' is not defined
name: reproduce test outputs with deepimagej 2.1.13 using onnx weights
reason: error
status: failed
traceback: ["  File \"/home/runner/work/models/models/scripts/check_rdf_and_test_model.py\",
    line 96, in test_resource\n    if not _validate_input_shape(tuple(ipt.shape),
    ipt_spec.shape):\n"]
